from PyQt6 import QtCore, QtGui, QtWidgets
import pymongo
from Controlador.ControllerCliente import ControllerCliente
from Controlador.ControllerEjemplar import ControllerEjemplar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 569)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 626, 569))
        self.stackedWidget.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_menu_principal = QtWidgets.QWidget()
        self.page_menu_principal.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"font: 300 16pt \"Perpetua Titling MT\";")
        self.page_menu_principal.setObjectName("page_menu_principal")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_menu_principal)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bt_cliente = QtWidgets.QPushButton(parent=self.page_menu_principal)
        self.bt_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_cliente.setObjectName("bt_cliente")
        self.gridLayout.addWidget(self.bt_cliente, 0, 0, 1, 1)
        self.bt_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_principal)
        self.bt_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_ejemplar.setObjectName("bt_ejemplar")
        self.gridLayout.addWidget(self.bt_ejemplar, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label_menu_principal = QtWidgets.QLabel(parent=self.page_menu_principal)
        self.label_menu_principal.setStyleSheet("font: 26pt \"Segoe UI\";")
        self.label_menu_principal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_menu_principal.setObjectName("label_menu_principal")
        self.gridLayout_2.addWidget(self.label_menu_principal, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.stackedWidget.addWidget(self.page_menu_principal)
        self.page_menu_cliente = QtWidgets.QWidget()
        self.page_menu_cliente.setStyleSheet("background-color:rgb(85, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.page_menu_cliente.setObjectName("page_menu_cliente")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_menu_cliente)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bt_alta_cliente = QtWidgets.QPushButton(parent=self.page_menu_cliente)
        self.bt_alta_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_alta_cliente.setObjectName("bt_alta_cliente")
        self.gridLayout_3.addWidget(self.bt_alta_cliente, 0, 0, 1, 1)
        self.bt_baja_cliente = QtWidgets.QPushButton(parent=self.page_menu_cliente)
        self.bt_baja_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_baja_cliente.setObjectName("bt_baja_cliente")
        self.gridLayout_3.addWidget(self.bt_baja_cliente, 1, 0, 1, 1)
        self.bt_modificacion_cliente = QtWidgets.QPushButton(parent=self.page_menu_cliente)
        self.bt_modificacion_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_modificacion_cliente.setObjectName("bt_modificacion_cliente")
        self.gridLayout_3.addWidget(self.bt_modificacion_cliente, 2, 0, 1, 1)
        self.bt_mostrar_cliente = QtWidgets.QPushButton(parent=self.page_menu_cliente)
        self.bt_mostrar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_mostrar_cliente.setObjectName("bt_mostrar_cliente")
        self.gridLayout_3.addWidget(self.bt_mostrar_cliente, 3, 0, 1, 1)
        self.bt_volver_cliente = QtWidgets.QPushButton(parent=self.page_menu_cliente)
        self.bt_volver_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_cliente.setObjectName("bt_volver_cliente")
        self.gridLayout_3.addWidget(self.bt_volver_cliente, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.page_menu_cliente)
        self.label.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.page_menu_cliente)
        self.page_menu_ejemplar = QtWidgets.QWidget()
        self.page_menu_ejemplar.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.page_menu_ejemplar.setObjectName("page_menu_ejemplar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_menu_ejemplar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_menu_ejemplar = QtWidgets.QLabel(parent=self.page_menu_ejemplar)
        self.label_menu_ejemplar.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_menu_ejemplar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_menu_ejemplar.setObjectName("label_menu_ejemplar")
        self.gridLayout_5.addWidget(self.label_menu_ejemplar, 0, 0, 1, 1)
        self.bt_alta_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_ejemplar)
        self.bt_alta_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_alta_ejemplar.setObjectName("bt_alta_ejemplar")
        self.gridLayout_5.addWidget(self.bt_alta_ejemplar, 1, 0, 1, 1)
        self.bt_baja_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_ejemplar)
        self.bt_baja_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_baja_ejemplar.setObjectName("bt_baja_ejemplar")
        self.gridLayout_5.addWidget(self.bt_baja_ejemplar, 2, 0, 1, 1)
        self.bt_modificacion_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_ejemplar)
        self.bt_modificacion_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_modificacion_ejemplar.setObjectName("bt_modificacion_ejemplar")
        self.gridLayout_5.addWidget(self.bt_modificacion_ejemplar, 3, 0, 1, 1)
        self.bt_mostrar_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_ejemplar)
        self.bt_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_mostrar_ejemplar.setObjectName("bt_mostrar_ejemplar")
        self.gridLayout_5.addWidget(self.bt_mostrar_ejemplar, 4, 0, 1, 1)
        self.bt_volver_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_ejemplar)
        self.bt_volver_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_ejemplar.setObjectName("bt_volver_ejemplar")
        self.gridLayout_5.addWidget(self.bt_volver_ejemplar, 5, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_menu_ejemplar)
        self.page_alta_cliente = QtWidgets.QWidget()
        self.page_alta_cliente.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.page_alta_cliente.setObjectName("page_alta_cliente")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_alta_cliente)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_2.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.le_nombre_cliente = QtWidgets.QLineEdit(parent=self.page_alta_cliente)
        self.le_nombre_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_nombre_cliente.setObjectName("le_nombre_cliente")
        self.gridLayout_6.addWidget(self.le_nombre_cliente, 0, 1, 1, 1)
        self.bt_guardar_cliente = QtWidgets.QPushButton(parent=self.page_alta_cliente)
        self.bt_guardar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_guardar_cliente.setObjectName("bt_guardar_cliente")
        self.gridLayout_6.addWidget(self.bt_guardar_cliente, 6, 0, 1, 2)
        self.label_dni = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_dni.setObjectName("label_dni")
        self.gridLayout_6.addWidget(self.label_dni, 2, 0, 1, 1)
        self.cb_medio = QtWidgets.QComboBox(parent=self.page_alta_cliente)
        self.cb_medio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_medio.setObjectName("cb_medio")
        self.cb_medio.addItem("")
        self.cb_medio.addItem("")
        self.gridLayout_6.addWidget(self.cb_medio, 5, 1, 1, 1)
        self.label_apellido = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_apellido.setObjectName("label_apellido")
        self.gridLayout_6.addWidget(self.label_apellido, 1, 0, 1, 1)
        self.label_nombre = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_nombre.setObjectName("label_nombre")
        self.gridLayout_6.addWidget(self.label_nombre, 0, 0, 1, 1)
        self.label_mail = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_mail.setObjectName("label_mail")
        self.gridLayout_6.addWidget(self.label_mail, 3, 0, 1, 1)
        self.le_telefono_cliente = QtWidgets.QLineEdit(parent=self.page_alta_cliente)
        self.le_telefono_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_telefono_cliente.setObjectName("le_telefono_cliente")
        self.gridLayout_6.addWidget(self.le_telefono_cliente, 4, 1, 1, 1)
        self.label_medio = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_medio.setObjectName("label_medio")
        self.gridLayout_6.addWidget(self.label_medio, 5, 0, 1, 1)
        self.le_mail_cliente = QtWidgets.QLineEdit(parent=self.page_alta_cliente)
        self.le_mail_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_mail_cliente.setObjectName("le_mail_cliente")
        self.gridLayout_6.addWidget(self.le_mail_cliente, 3, 1, 1, 1)
        self.le_dni_cliente = QtWidgets.QLineEdit(parent=self.page_alta_cliente)
        self.le_dni_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_dni_cliente.setObjectName("le_dni_cliente")
        self.gridLayout_6.addWidget(self.le_dni_cliente, 2, 1, 1, 1)
        self.le_apellido_cliente = QtWidgets.QLineEdit(parent=self.page_alta_cliente)
        self.le_apellido_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_apellido_cliente.setObjectName("le_apellido_cliente")
        self.gridLayout_6.addWidget(self.le_apellido_cliente, 1, 1, 1, 1)
        self.label_telefono = QtWidgets.QLabel(parent=self.page_alta_cliente)
        self.label_telefono.setObjectName("label_telefono")
        self.gridLayout_6.addWidget(self.label_telefono, 4, 0, 1, 1)
        self.bt_volver_menu_alta_cliente = QtWidgets.QPushButton(parent=self.page_alta_cliente)
        self.bt_volver_menu_alta_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_menu_alta_cliente.setObjectName("bt_volver_menu_alta_cliente")
        self.gridLayout_6.addWidget(self.bt_volver_menu_alta_cliente, 7, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.page_alta_cliente)
        self.page_baja_cliente = QtWidgets.QWidget()
        self.page_baja_cliente.setObjectName("page_baja_cliente")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_baja_cliente)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_3 = QtWidgets.QLabel(parent=self.page_baja_cliente)
        self.label_3.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_4 = QtWidgets.QLabel(parent=self.page_baja_cliente)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_dni_baja_cliente = QtWidgets.QLineEdit(parent=self.page_baja_cliente)
        self.le_dni_baja_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_dni_baja_cliente.setObjectName("le_dni_baja_cliente")
        self.gridLayout_11.addWidget(self.le_dni_baja_cliente, 0, 1, 1, 1)
        self.bt_eliminar_cliente = QtWidgets.QPushButton(parent=self.page_baja_cliente)
        self.bt_eliminar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_eliminar_cliente.setObjectName("bt_eliminar_cliente")
        self.gridLayout_11.addWidget(self.bt_eliminar_cliente, 0, 2, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_baja_cliente)
        self.tableWidget.setRowCount(20)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_10.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.bt_volver_baja_cliente = QtWidgets.QPushButton(parent=self.page_baja_cliente)
        self.bt_volver_baja_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_baja_cliente.setObjectName("bt_volver_baja_cliente")
        self.gridLayout_10.addWidget(self.bt_volver_baja_cliente, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_13)
        self.stackedWidget.addWidget(self.page_baja_cliente)
        self.page_baja_ejemplar = QtWidgets.QWidget()
        self.page_baja_ejemplar.setObjectName("page_baja_ejemplar")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_baja_ejemplar)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_31 = QtWidgets.QGridLayout()
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_29 = QtWidgets.QLabel(parent=self.page_baja_ejemplar)
        self.label_29.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_31.addWidget(self.label_29, 0, 0, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_30 = QtWidgets.QLabel(parent=self.page_baja_ejemplar)
        self.label_30.setObjectName("label_30")
        self.gridLayout_28.addWidget(self.label_30, 0, 0, 1, 1)
        self.le_titulo_baja_ejemplar = QtWidgets.QLineEdit(parent=self.page_baja_ejemplar)
        self.le_titulo_baja_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_titulo_baja_ejemplar.setObjectName("le_titulo_baja_ejemplar")
        self.gridLayout_28.addWidget(self.le_titulo_baja_ejemplar, 0, 1, 1, 1)
        self.bt_eliminar_ejemplar = QtWidgets.QPushButton(parent=self.page_baja_ejemplar)
        self.bt_eliminar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_eliminar_ejemplar.setObjectName("bt_eliminar_ejemplar")
        self.gridLayout_28.addWidget(self.bt_eliminar_ejemplar, 0, 2, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.page_baja_ejemplar)
        self.tableWidget_3.setRowCount(20)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.gridLayout_29.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.bt_volver_baja_ejemplar = QtWidgets.QPushButton(parent=self.page_baja_ejemplar)
        self.bt_volver_baja_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_baja_ejemplar.setObjectName("bt_volver_baja_ejemplar")
        self.gridLayout_29.addWidget(self.bt_volver_baja_ejemplar, 1, 0, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_29, 1, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 1, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_31)
        self.stackedWidget.addWidget(self.page_baja_ejemplar)
        self.page_menu_modificacion_cliente = QtWidgets.QWidget()
        self.page_menu_modificacion_cliente.setObjectName("page_menu_modificacion_cliente")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_menu_modificacion_cliente)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_9 = QtWidgets.QLabel(parent=self.page_menu_modificacion_cliente)
        self.label_9.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_10 = QtWidgets.QLabel(parent=self.page_menu_modificacion_cliente)
        self.label_10.setObjectName("label_10")
        self.gridLayout_15.addWidget(self.label_10, 0, 0, 1, 1)
        self.le_dni_modificar_cliente = QtWidgets.QLineEdit(parent=self.page_menu_modificacion_cliente)
        self.le_dni_modificar_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_dni_modificar_cliente.setObjectName("le_dni_modificar_cliente")
        self.gridLayout_15.addWidget(self.le_dni_modificar_cliente, 0, 1, 1, 1)
        self.bt_modificar_modificar_cliente = QtWidgets.QPushButton(parent=self.page_menu_modificacion_cliente)
        self.bt_modificar_modificar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_modificar_modificar_cliente.setObjectName("bt_modificar_modificar_cliente")
        self.gridLayout_15.addWidget(self.bt_modificar_modificar_cliente, 0, 2, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.page_menu_modificacion_cliente)
        self.tableWidget_2.setRowCount(20)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.gridLayout_14.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.bt_volver_menu_modificacion_cliente = QtWidgets.QPushButton(parent=self.page_menu_modificacion_cliente)
        self.bt_volver_menu_modificacion_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_menu_modificacion_cliente.setObjectName("bt_volver_menu_modificacion_cliente")
        self.gridLayout_14.addWidget(self.bt_volver_menu_modificacion_cliente, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 1, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_17)
        self.stackedWidget.addWidget(self.page_menu_modificacion_cliente)
        self.page_menu_modificacion_ejemplar = QtWidgets.QWidget()
        self.page_menu_modificacion_ejemplar.setObjectName("page_menu_modificacion_ejemplar")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_menu_modificacion_ejemplar)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.label_36 = QtWidgets.QLabel(parent=self.page_menu_modificacion_ejemplar)
        self.label_36.setStyleSheet("\n"
"font: 36pt \"Segoe UI\";")
        self.label_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_43.addWidget(self.label_36, 0, 0, 1, 1)
        self.gridLayout_42 = QtWidgets.QGridLayout()
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.label_37 = QtWidgets.QLabel(parent=self.page_menu_modificacion_ejemplar)
        self.label_37.setObjectName("label_37")
        self.gridLayout_40.addWidget(self.label_37, 0, 0, 1, 1)
        self.le_titutlo_modificar_ejemplar = QtWidgets.QLineEdit(parent=self.page_menu_modificacion_ejemplar)
        self.le_titutlo_modificar_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_titutlo_modificar_ejemplar.setObjectName("le_titutlo_modificar_ejemplar")
        self.gridLayout_40.addWidget(self.le_titutlo_modificar_ejemplar, 0, 1, 1, 1)
        self.bt_modificar_modificar_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_modificacion_ejemplar)
        self.bt_modificar_modificar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_modificar_modificar_ejemplar.setObjectName("bt_modificar_modificar_ejemplar")
        self.gridLayout_40.addWidget(self.bt_modificar_modificar_ejemplar, 0, 2, 1, 1)
        self.gridLayout_41.addLayout(self.gridLayout_40, 0, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.page_menu_modificacion_ejemplar)
        self.tableWidget_4.setRowCount(20)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.gridLayout_41.addWidget(self.tableWidget_4, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_41, 0, 0, 1, 1)
        self.bt_volver_menu_modificacion_ejemplar = QtWidgets.QPushButton(parent=self.page_menu_modificacion_ejemplar)
        self.bt_volver_menu_modificacion_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_menu_modificacion_ejemplar.setObjectName("bt_volver_menu_modificacion_ejemplar")
        self.gridLayout_42.addWidget(self.bt_volver_menu_modificacion_ejemplar, 1, 0, 1, 1)
        self.gridLayout_43.addLayout(self.gridLayout_42, 1, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_43)
        self.stackedWidget.addWidget(self.page_menu_modificacion_ejemplar)
        self.page_modificacion_cliente = QtWidgets.QWidget()
        self.page_modificacion_cliente.setObjectName("page_modificacion_cliente")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_modificacion_cliente)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_11 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_11.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_21.addWidget(self.label_11, 0, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_19 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_19.setObjectName("label_19")
        self.gridLayout_18.addWidget(self.label_19, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_13.setObjectName("label_13")
        self.gridLayout_18.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_23.setObjectName("label_23")
        self.gridLayout_18.addWidget(self.label_23, 11, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_18.setObjectName("label_18")
        self.gridLayout_18.addWidget(self.label_18, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_17.setObjectName("label_17")
        self.gridLayout_18.addWidget(self.label_17, 5, 0, 1, 1)
        self.le_apellido_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_cliente)
        self.le_apellido_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_apellido_nuevo.setObjectName("le_apellido_nuevo")
        self.gridLayout_18.addWidget(self.le_apellido_nuevo, 3, 1, 1, 1)
        self.le_telefono_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_cliente)
        self.le_telefono_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_telefono_nuevo.setObjectName("le_telefono_nuevo")
        self.gridLayout_18.addWidget(self.le_telefono_nuevo, 7, 1, 1, 1)
        self.le_dni_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_cliente)
        self.le_dni_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_dni_nuevo.setObjectName("le_dni_nuevo")
        self.gridLayout_18.addWidget(self.le_dni_nuevo, 5, 1, 1, 1)
        self.le_mail_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_cliente)
        self.le_mail_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_mail_nuevo.setObjectName("le_mail_nuevo")
        self.gridLayout_18.addWidget(self.le_mail_nuevo, 9, 1, 1, 1)
        self.lb_telefono_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_telefono_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_telefono_actual.setText("")
        self.lb_telefono_actual.setObjectName("lb_telefono_actual")
        self.gridLayout_18.addWidget(self.lb_telefono_actual, 6, 1, 1, 1)
        self.cb_medio_nuevo = QtWidgets.QComboBox(parent=self.page_modificacion_cliente)
        self.cb_medio_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_medio_nuevo.setObjectName("cb_medio_nuevo")
        self.cb_medio_nuevo.addItem("")
        self.cb_medio_nuevo.addItem("")
        self.gridLayout_18.addWidget(self.cb_medio_nuevo, 11, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 10, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_21.setObjectName("label_21")
        self.gridLayout_18.addWidget(self.label_21, 9, 0, 1, 1)
        self.lb_apellido_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_apellido_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_apellido_actual.setText("")
        self.lb_apellido_actual.setObjectName("lb_apellido_actual")
        self.gridLayout_18.addWidget(self.lb_apellido_actual, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_15.setObjectName("label_15")
        self.gridLayout_18.addWidget(self.label_15, 3, 0, 1, 1)
        self.lb_mail_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_mail_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_mail_actual.setText("")
        self.lb_mail_actual.setObjectName("lb_mail_actual")
        self.gridLayout_18.addWidget(self.lb_mail_actual, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_12.setObjectName("label_12")
        self.gridLayout_18.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_20.setObjectName("label_20")
        self.gridLayout_18.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_14.setObjectName("label_14")
        self.gridLayout_18.addWidget(self.label_14, 2, 0, 1, 1)
        self.le_nombre_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_cliente)
        self.le_nombre_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_nombre_nuevo.setObjectName("le_nombre_nuevo")
        self.gridLayout_18.addWidget(self.le_nombre_nuevo, 1, 1, 1, 1)
        self.lb_nombre_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_nombre_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_nombre_actual.setText("")
        self.lb_nombre_actual.setObjectName("lb_nombre_actual")
        self.gridLayout_18.addWidget(self.lb_nombre_actual, 0, 1, 1, 1)
        self.lb_medio_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_medio_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_medio_actual.setText("")
        self.lb_medio_actual.setObjectName("lb_medio_actual")
        self.gridLayout_18.addWidget(self.lb_medio_actual, 10, 1, 1, 1)
        self.lb_dni_actual = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.lb_dni_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_dni_actual.setText("")
        self.lb_dni_actual.setObjectName("lb_dni_actual")
        self.gridLayout_18.addWidget(self.lb_dni_actual, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.page_modificacion_cliente)
        self.label_16.setObjectName("label_16")
        self.gridLayout_18.addWidget(self.label_16, 4, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.bt_volver_modificacion_cliente = QtWidgets.QPushButton(parent=self.page_modificacion_cliente)
        self.bt_volver_modificacion_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_modificacion_cliente.setObjectName("bt_volver_modificacion_cliente")
        self.gridLayout_19.addWidget(self.bt_volver_modificacion_cliente, 0, 0, 1, 1)
        self.bt_guardar_modificacion_cliente = QtWidgets.QPushButton(parent=self.page_modificacion_cliente)
        self.bt_guardar_modificacion_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_guardar_modificacion_cliente.setObjectName("bt_guardar_modificacion_cliente")
        self.gridLayout_19.addWidget(self.bt_guardar_modificacion_cliente, 0, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 1, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 1, 0, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_21)
        self.stackedWidget.addWidget(self.page_modificacion_cliente)
        self.page_modificacion_ejemplar = QtWidgets.QWidget()
        self.page_modificacion_ejemplar.setObjectName("page_modificacion_ejemplar")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_modificacion_ejemplar)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.gridLayout_55 = QtWidgets.QGridLayout()
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.label_38 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_38.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_38.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_55.addWidget(self.label_38, 0, 0, 1, 1)
        self.gridLayout_54 = QtWidgets.QGridLayout()
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.gridLayout_53 = QtWidgets.QGridLayout()
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.gridLayout_51 = QtWidgets.QGridLayout()
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.label_39 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_39.setObjectName("label_39")
        self.gridLayout_51.addWidget(self.label_39, 0, 0, 1, 1)
        self.lb_titulo_actual = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.lb_titulo_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_titulo_actual.setText("")
        self.lb_titulo_actual.setObjectName("lb_titulo_actual")
        self.gridLayout_51.addWidget(self.lb_titulo_actual, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_51, 0, 0, 1, 1)
        self.gridLayout_50 = QtWidgets.QGridLayout()
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.label_40 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_40.setObjectName("label_40")
        self.gridLayout_50.addWidget(self.label_40, 0, 0, 1, 1)
        self.le_titulo_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_ejemplar)
        self.le_titulo_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_titulo_nuevo.setObjectName("le_titulo_nuevo")
        self.gridLayout_50.addWidget(self.le_titulo_nuevo, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_50, 1, 0, 1, 1)
        self.gridLayout_49 = QtWidgets.QGridLayout()
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.label_41 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_41.setObjectName("label_41")
        self.gridLayout_49.addWidget(self.label_41, 0, 0, 1, 1)
        self.lb_autor_actual = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.lb_autor_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_autor_actual.setText("")
        self.lb_autor_actual.setObjectName("lb_autor_actual")
        self.gridLayout_49.addWidget(self.lb_autor_actual, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_49, 2, 0, 1, 1)
        self.gridLayout_48 = QtWidgets.QGridLayout()
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.label_42 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_42.setObjectName("label_42")
        self.gridLayout_48.addWidget(self.label_42, 0, 0, 1, 1)
        self.le_autor_nuevo = QtWidgets.QLineEdit(parent=self.page_modificacion_ejemplar)
        self.le_autor_nuevo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_autor_nuevo.setObjectName("le_autor_nuevo")
        self.gridLayout_48.addWidget(self.le_autor_nuevo, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_48, 3, 0, 1, 1)
        self.gridLayout_47 = QtWidgets.QGridLayout()
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.label_43 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_43.setObjectName("label_43")
        self.gridLayout_47.addWidget(self.label_43, 0, 0, 1, 1)
        self.lb_fechaPublicacion_actual = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.lb_fechaPublicacion_actual.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"")
        self.lb_fechaPublicacion_actual.setText("")
        self.lb_fechaPublicacion_actual.setObjectName("lb_fechaPublicacion_actual")
        self.gridLayout_47.addWidget(self.lb_fechaPublicacion_actual, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_47, 4, 0, 1, 1)
        self.gridLayout_46 = QtWidgets.QGridLayout()
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.label_44 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_44.setObjectName("label_44")
        self.gridLayout_46.addWidget(self.label_44, 0, 0, 1, 1)
        self.le_fechaPublicacion_nueva = QtWidgets.QLineEdit(parent=self.page_modificacion_ejemplar)
        self.le_fechaPublicacion_nueva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_fechaPublicacion_nueva.setObjectName("le_fechaPublicacion_nueva")
        self.gridLayout_46.addWidget(self.le_fechaPublicacion_nueva, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_46, 5, 0, 1, 1)
        self.gridLayout_45 = QtWidgets.QGridLayout()
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.label_48 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_48.setObjectName("label_48")
        self.gridLayout_45.addWidget(self.label_48, 0, 0, 1, 1)
        self.lb_categoria_actual = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.lb_categoria_actual.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_categoria_actual.setText("")
        self.lb_categoria_actual.setObjectName("lb_categoria_actual")
        self.gridLayout_45.addWidget(self.lb_categoria_actual, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_45, 6, 0, 1, 1)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_50 = QtWidgets.QLabel(parent=self.page_modificacion_ejemplar)
        self.label_50.setObjectName("label_50")
        self.gridLayout_44.addWidget(self.label_50, 0, 0, 1, 1)
        self.le_categoria_nueva = QtWidgets.QLineEdit(parent=self.page_modificacion_ejemplar)
        self.le_categoria_nueva.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_categoria_nueva.setObjectName("le_categoria_nueva")
        self.gridLayout_44.addWidget(self.le_categoria_nueva, 0, 1, 1, 1)
        self.gridLayout_53.addLayout(self.gridLayout_44, 7, 0, 1, 1)
        self.gridLayout_54.addLayout(self.gridLayout_53, 0, 0, 1, 1)
        self.gridLayout_52 = QtWidgets.QGridLayout()
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.bt_volver_modificacion_ejemplar = QtWidgets.QPushButton(parent=self.page_modificacion_ejemplar)
        self.bt_volver_modificacion_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_modificacion_ejemplar.setObjectName("bt_volver_modificacion_ejemplar")
        self.gridLayout_52.addWidget(self.bt_volver_modificacion_ejemplar, 0, 0, 1, 1)
        self.bt_guardar_modificacion_ejemplar = QtWidgets.QPushButton(parent=self.page_modificacion_ejemplar)
        self.bt_guardar_modificacion_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_guardar_modificacion_ejemplar.setObjectName("bt_guardar_modificacion_ejemplar")
        self.gridLayout_52.addWidget(self.bt_guardar_modificacion_ejemplar, 0, 1, 1, 1)
        self.gridLayout_54.addLayout(self.gridLayout_52, 1, 0, 1, 1)
        self.gridLayout_55.addLayout(self.gridLayout_54, 1, 0, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_55)
        self.stackedWidget.addWidget(self.page_modificacion_ejemplar)
        self.page_mostrar_cliente = QtWidgets.QWidget()
        self.page_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 16pt \"Segoe UI\";")
        self.page_mostrar_cliente.setObjectName("page_mostrar_cliente")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_mostrar_cliente)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_8 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_8.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_24.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_dni_2 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_dni_2.setObjectName("label_dni_2")
        self.gridLayout_9.addWidget(self.label_dni_2, 0, 0, 1, 1)
        self.le_dni_mostrar_cliente = QtWidgets.QLineEdit(parent=self.page_mostrar_cliente)
        self.le_dni_mostrar_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_dni_mostrar_cliente.setObjectName("le_dni_mostrar_cliente")
        self.gridLayout_9.addWidget(self.le_dni_mostrar_cliente, 0, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_nombre_2 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_nombre_2.setObjectName("label_nombre_2")
        self.gridLayout_7.addWidget(self.label_nombre_2, 0, 0, 1, 1)
        self.lb_nombre_mostrar_cliente = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.lb_nombre_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_nombre_mostrar_cliente.setText("")
        self.lb_nombre_mostrar_cliente.setObjectName("lb_nombre_mostrar_cliente")
        self.gridLayout_7.addWidget(self.lb_nombre_mostrar_cliente, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.lb_apellido_mostrar_cliente = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.lb_apellido_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_apellido_mostrar_cliente.setText("")
        self.lb_apellido_mostrar_cliente.setObjectName("lb_apellido_mostrar_cliente")
        self.gridLayout_7.addWidget(self.lb_apellido_mostrar_cliente, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 2, 0, 1, 1)
        self.lb_telefono_mostrar_cliente = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.lb_telefono_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_telefono_mostrar_cliente.setText("")
        self.lb_telefono_mostrar_cliente.setObjectName("lb_telefono_mostrar_cliente")
        self.gridLayout_7.addWidget(self.lb_telefono_mostrar_cliente, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 3, 0, 1, 1)
        self.lb_mail_mostrar_cliente = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.lb_mail_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_mail_mostrar_cliente.setText("")
        self.lb_mail_mostrar_cliente.setObjectName("lb_mail_mostrar_cliente")
        self.gridLayout_7.addWidget(self.lb_mail_mostrar_cliente, 3, 1, 1, 1)
        self.label_medio_2 = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.label_medio_2.setObjectName("label_medio_2")
        self.gridLayout_7.addWidget(self.label_medio_2, 4, 0, 1, 1)
        self.lb_medio_mostrar_cliente = QtWidgets.QLabel(parent=self.page_mostrar_cliente)
        self.lb_medio_mostrar_cliente.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_medio_mostrar_cliente.setText("")
        self.lb_medio_mostrar_cliente.setObjectName("lb_medio_mostrar_cliente")
        self.gridLayout_7.addWidget(self.lb_medio_mostrar_cliente, 4, 1, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.bt_volver_mostrar_cliente = QtWidgets.QPushButton(parent=self.page_mostrar_cliente)
        self.bt_volver_mostrar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_mostrar_cliente.setObjectName("bt_volver_mostrar_cliente")
        self.gridLayout_8.addWidget(self.bt_volver_mostrar_cliente, 0, 0, 1, 1)
        self.bt_mostrar_mostrar_cliente = QtWidgets.QPushButton(parent=self.page_mostrar_cliente)
        self.bt_mostrar_mostrar_cliente.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_mostrar_mostrar_cliente.setObjectName("bt_mostrar_mostrar_cliente")
        self.gridLayout_8.addWidget(self.bt_mostrar_mostrar_cliente, 0, 1, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_24)
        self.stackedWidget.addWidget(self.page_mostrar_cliente)
        self.page_mostrar_ejemplar = QtWidgets.QWidget()
        self.page_mostrar_ejemplar.setObjectName("page_mostrar_ejemplar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_mostrar_ejemplar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_31 = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.label_31.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_39.addWidget(self.label_31, 0, 0, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_32 = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.label_32.setObjectName("label_32")
        self.gridLayout_32.addWidget(self.label_32, 0, 0, 1, 1)
        self.le_titulo_mostrar_ejemplar = QtWidgets.QLineEdit(parent=self.page_mostrar_ejemplar)
        self.le_titulo_mostrar_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_titulo_mostrar_ejemplar.setObjectName("le_titulo_mostrar_ejemplar")
        self.gridLayout_32.addWidget(self.le_titulo_mostrar_ejemplar, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_33 = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.label_33.setObjectName("label_33")
        self.gridLayout_33.addWidget(self.label_33, 0, 0, 1, 1)
        self.lb_autor_mostrar_ejemplar = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.lb_autor_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_autor_mostrar_ejemplar.setText("")
        self.lb_autor_mostrar_ejemplar.setObjectName("lb_autor_mostrar_ejemplar")
        self.gridLayout_33.addWidget(self.lb_autor_mostrar_ejemplar, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_33, 1, 0, 1, 1)
        self.gridLayout_34 = QtWidgets.QGridLayout()
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.label_34 = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.label_34.setObjectName("label_34")
        self.gridLayout_34.addWidget(self.label_34, 0, 0, 1, 1)
        self.lb_fechaPublicacion_mostrar_ejemplar = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.lb_fechaPublicacion_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_fechaPublicacion_mostrar_ejemplar.setText("")
        self.lb_fechaPublicacion_mostrar_ejemplar.setObjectName("lb_fechaPublicacion_mostrar_ejemplar")
        self.gridLayout_34.addWidget(self.lb_fechaPublicacion_mostrar_ejemplar, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_34, 2, 0, 1, 1)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.label_35 = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.label_35.setObjectName("label_35")
        self.gridLayout_35.addWidget(self.label_35, 0, 0, 1, 1)
        self.lb_categoria_mostrar_ejemplar = QtWidgets.QLabel(parent=self.page_mostrar_ejemplar)
        self.lb_categoria_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.lb_categoria_mostrar_ejemplar.setText("")
        self.lb_categoria_mostrar_ejemplar.setObjectName("lb_categoria_mostrar_ejemplar")
        self.gridLayout_35.addWidget(self.lb_categoria_mostrar_ejemplar, 0, 1, 1, 1)
        self.gridLayout_37.addLayout(self.gridLayout_35, 3, 0, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_37, 0, 0, 1, 1)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.bt_volver_mostrar_ejemplar = QtWidgets.QPushButton(parent=self.page_mostrar_ejemplar)
        self.bt_volver_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_mostrar_ejemplar.setObjectName("bt_volver_mostrar_ejemplar")
        self.gridLayout_36.addWidget(self.bt_volver_mostrar_ejemplar, 0, 0, 1, 1)
        self.bt_mostrar_mostrar_ejemplar = QtWidgets.QPushButton(parent=self.page_mostrar_ejemplar)
        self.bt_mostrar_mostrar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_mostrar_mostrar_ejemplar.setObjectName("bt_mostrar_mostrar_ejemplar")
        self.gridLayout_36.addWidget(self.bt_mostrar_mostrar_ejemplar, 0, 1, 1, 1)
        self.gridLayout_38.addLayout(self.gridLayout_36, 1, 0, 1, 1)
        self.gridLayout_39.addLayout(self.gridLayout_38, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_39)
        self.stackedWidget.addWidget(self.page_mostrar_ejemplar)
        self.page_alta_ejemplar = QtWidgets.QWidget()
        self.page_alta_ejemplar.setObjectName("page_alta_ejemplar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_alta_ejemplar)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_24 = QtWidgets.QLabel(parent=self.page_alta_ejemplar)
        self.label_24.setStyleSheet("font: 36pt \"Segoe UI\";")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_27.addWidget(self.label_24, 0, 0, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_25 = QtWidgets.QLabel(parent=self.page_alta_ejemplar)
        self.label_25.setObjectName("label_25")
        self.gridLayout_25.addWidget(self.label_25, 0, 0, 1, 1)
        self.le_titulo_ejemplar = QtWidgets.QLineEdit(parent=self.page_alta_ejemplar)
        self.le_titulo_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_titulo_ejemplar.setObjectName("le_titulo_ejemplar")
        self.gridLayout_25.addWidget(self.le_titulo_ejemplar, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(parent=self.page_alta_ejemplar)
        self.label_26.setObjectName("label_26")
        self.gridLayout_25.addWidget(self.label_26, 1, 0, 1, 1)
        self.le_autor_ejemplar = QtWidgets.QLineEdit(parent=self.page_alta_ejemplar)
        self.le_autor_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_autor_ejemplar.setObjectName("le_autor_ejemplar")
        self.gridLayout_25.addWidget(self.le_autor_ejemplar, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(parent=self.page_alta_ejemplar)
        self.label_27.setObjectName("label_27")
        self.gridLayout_25.addWidget(self.label_27, 2, 0, 1, 1)
        self.le_fecha_publicacion_ejemplar = QtWidgets.QLineEdit(parent=self.page_alta_ejemplar)
        self.le_fecha_publicacion_ejemplar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.le_fecha_publicacion_ejemplar.setObjectName("le_fecha_publicacion_ejemplar")
        self.gridLayout_25.addWidget(self.le_fecha_publicacion_ejemplar, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(parent=self.page_alta_ejemplar)
        self.label_28.setObjectName("label_28")
        self.gridLayout_25.addWidget(self.label_28, 3, 0, 1, 1)
        self.cb_categoria = QtWidgets.QComboBox(parent=self.page_alta_ejemplar)
        self.cb_categoria.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cb_categoria.setObjectName("cb_categoria")
        self.cb_categoria.addItem("")
        self.cb_categoria.addItem("")
        self.cb_categoria.addItem("")
        self.gridLayout_25.addWidget(self.cb_categoria, 3, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 0, 0, 1, 2)
        self.bt_volver_menu_alta_ejemplar = QtWidgets.QPushButton(parent=self.page_alta_ejemplar)
        self.bt_volver_menu_alta_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_volver_menu_alta_ejemplar.setObjectName("bt_volver_menu_alta_ejemplar")
        self.gridLayout_26.addWidget(self.bt_volver_menu_alta_ejemplar, 1, 0, 1, 1)
        self.bt_guardar_ejemplar = QtWidgets.QPushButton(parent=self.page_alta_ejemplar)
        self.bt_guardar_ejemplar.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.bt_guardar_ejemplar.setObjectName("bt_guardar_ejemplar")
        self.gridLayout_26.addWidget(self.bt_guardar_ejemplar, 1, 1, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 1, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_27)
        self.stackedWidget.addWidget(self.page_alta_ejemplar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.stackedWidget.setCurrentWidget(self.page_menu_principal)

        ############################################ acciones de los BOTONES CLIENTES #############################################
        self.bt_guardar_cliente.clicked.connect(self.guardarCliente)
        self.bt_mostrar_mostrar_cliente.clicked.connect(self.mostrarCliente)
        self.bt_guardar_modificacion_cliente.clicked.connect(self.guardarModificacionCliente)
        self.bt_eliminar_cliente.clicked.connect(self.eliminarCliente)
        self.bt_cliente.clicked.connect(self.pgMenuCliente)
        self.bt_alta_cliente.clicked.connect(self.pgMenuClienteAlta)
        self.bt_baja_cliente.clicked.connect(self.pgMenuClienteBaja)
        self.bt_modificacion_cliente.clicked.connect(self.pgMenuClienteModif)
        self.bt_mostrar_cliente.clicked.connect(self.pgMenuClienteMostrarCliente)
        self.bt_volver_cliente.clicked.connect(self.pgMenuClienteVolver)
        self.bt_volver_menu_alta_cliente.clicked.connect(self.pgMenuAltaClienteVolver)
        self.bt_volver_baja_cliente.clicked.connect(self.pgMenuBajaClienteVolver)
        self.bt_volver_menu_modificacion_cliente.clicked.connect(self.pgMenuModifClienteVolver)
        self.bt_volver_mostrar_cliente.clicked.connect(self.pgMostrarClienteVolver)
        self.bt_modificar_modificar_cliente.clicked.connect(self.pgModificacionCliente)
        self.bt_volver_modificacion_cliente.clicked.connect(self.pgMenuModificacionCliente)

        ## acciones de los BOTONES EJEMPLARES ##
        self.bt_guardar_ejemplar.clicked.connect(self.guardarEjemplar)
        self.bt_mostrar_mostrar_ejemplar.clicked.connect(self.mostarEjemplar)
        self.bt_guardar_modificacion_ejemplar.clicked.connect(self.guardarModificacionEjemplar)
        self.bt_eliminar_ejemplar.clicked.connect(self.eliminarEjemplar)
        self.bt_ejemplar.clicked.connect(self.pgMenuEjemplar)
        self.bt_alta_ejemplar.clicked.connect(self.pgMenuEjemplarAlta)
        self.bt_baja_ejemplar.clicked.connect(self.pgMenuEjemplarBaja)
        self.bt_modificacion_ejemplar.clicked.connect(self.pgMenuEjemplarModif)
        self.bt_mostrar_ejemplar.clicked.connect(self.pgMenuEjemplarMostrarEjemplar)
        self.bt_volver_ejemplar.clicked.connect(self.pgMenuEjemplarVolver)
        self.bt_volver_menu_alta_ejemplar.clicked.connect(self.pgMenuAltaEjemplarVolver)
        self.bt_volver_baja_ejemplar.clicked.connect(self.pgMenuBajaEjemplarVolver)
        self.bt_volver_menu_modificacion_ejemplar.clicked.connect(self.pgMenuModifEjemplarVolver)
        self.bt_volver_mostrar_ejemplar.clicked.connect(self.pgMostrarEjemplarVolver)
        self.bt_modificar_modificar_ejemplar.clicked.connect(self.pgModificacionEjemplar)
        self.bt_volver_modificacion_ejemplar.clicked.connect(self.pgMenuModificacionEjemplar)

    ## funciones de los botones ##

    ##funciones de clientes  METODOS  
    def pgMenuCliente(self): self.stackedWidget.setCurrentWidget(self.page_menu_cliente) 
    def pgMenuClienteAlta(self): self.stackedWidget.setCurrentWidget(self.page_alta_cliente)
    def pgMenuClienteMostrarCliente(self): self.stackedWidget.setCurrentWidget(self.page_mostrar_cliente)
    def pgMenuClienteVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_principal)
    def pgMenuAltaClienteVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_cliente)
    def pgMenuBajaClienteVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_cliente)
    def pgMenuModifClienteVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_cliente)
    def pgModifClienteVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_cliente)
    def pgMenuModificacionCliente(self): self.stackedWidget.setCurrentWidget(self.page_menu_modificacion_cliente)

    def pgMostrarClienteVolver(self): 
        self.stackedWidget.setCurrentWidget(self.page_menu_cliente)
        self.lb_nombre_mostrar_cliente.clear()
        self.lb_apellido_mostrar_cliente.clear()
        self.lb_telefono_mostrar_cliente.clear()
        self.lb_mail_mostrar_cliente.clear()
        self.lb_medio_mostrar_cliente.clear()

    def guardarCliente(self):
        cliente = ControllerCliente()
        if self.cb_medio.currentText() == "SMS":
            cliente.altaCliente(
            self.le_nombre_cliente.text(),
            self.le_apellido_cliente.text(),
            self.le_dni_cliente.text(),
            self.le_mail_cliente.text(),
            self.le_telefono_cliente.text(),
            medio = "SMS")
        elif self.cb_medio.currentText() == "MAIL":
            cliente.altaCliente(
            self.le_nombre_cliente.text(),
            self.le_apellido_cliente.text(),
            self.le_dni_cliente.text(),
            self.le_mail_cliente.text(),
            self.le_telefono_cliente.text(),
            medio = "MAIL")
        else:
            print("Datos Incorrectos")
            
        cliente.mostrarClientes()
        self.le_nombre_cliente.clear(),
        self.le_apellido_cliente.clear(),
        self.le_dni_cliente.clear(),
        self.le_mail_cliente.clear(),
        self.le_telefono_cliente.clear(),

    def mostrarCliente(self):
        c = pymongo.MongoClient(serverSelectionTimeoutMS = 1000)
        db = c.get_database("Biblioteca")
        coleccionClientes = db.get_collection("Clientes")
       
        cliente = coleccionClientes.find_one({"dni": self.le_dni_mostrar_cliente.text()})
        print(cliente)

        self.lb_nombre_mostrar_cliente.setText(str(cliente["nombre"]))
        self.lb_apellido_mostrar_cliente.setText(str(cliente["apellido"]))
        self.lb_telefono_mostrar_cliente.setText(str(cliente["telefono"]))
        self.lb_mail_mostrar_cliente.setText(str(cliente["mail"]))
        self.lb_medio_mostrar_cliente.setText(str(cliente["medio"]))

        self.le_dni_mostrar_cliente.clear()
        

    def guardarModificacionCliente(self):
        nombre = self.lb_nombre_actual.text()
        apellido = self.lb_apellido_actual.text()
        dni = self.lb_dni_actual.text()
        telefono = self.lb_telefono_actual.text()
        mail = self.lb_mail_actual.text()
        medio = self.lb_medio_actual.text()

        if self.le_nombre_nuevo.text() != "": 
            nombre = self.le_nombre_nuevo.text()
        if self.le_apellido_nuevo.text() != "": 
            apellido = self.le_apellido_nuevo.text()
        if self.le_dni_nuevo.text() != "": 
            dni = self.le_dni_nuevo.text()
        if self.le_telefono_nuevo.text() != "": 
            telefono = self.le_telefono_nuevo.text()
        if self.le_mail_nuevo.text() != "": 
            mail = self.le_mail_nuevo.text()
        if self.cb_medio_nuevo.currentText() != "-": 
            medio = self.cb_medio_nuevo.currentText()

        cliente = ControllerCliente()
        cliente.bajaCliente(self.lb_dni_actual.text())
        cliente.altaCliente(nombre,apellido,dni,telefono,mail,medio)

        self.lb_nombre_actual.clear()
        self.le_nombre_nuevo.clear()
        self.lb_apellido_actual.clear()
        self.le_apellido_nuevo.clear()
        self.lb_dni_actual.clear()
        self.le_dni_nuevo.clear()
        self.lb_telefono_actual.clear()
        self.le_telefono_nuevo.clear()
        self.lb_mail_actual.clear()
        self.le_mail_nuevo.clear()

    def pgModificacionCliente(self):
        self.stackedWidget.setCurrentWidget(self.page_modificacion_cliente)
        c = pymongo.MongoClient(serverSelectionTimeoutMS = 1000)
        db = c.get_database("Biblioteca")
        coleccionClientes = db.get_collection("Clientes")
        cliente = coleccionClientes.find_one({"dni": self.le_dni_modificar_cliente.text()})

        self.lb_nombre_actual.setText(str(cliente["nombre"]))
        self.lb_apellido_actual.setText(str(cliente["apellido"]))
        self.lb_dni_actual.setText(str(cliente["dni"]))
        self.lb_telefono_actual.setText(str(cliente["telefono"]))
        self.lb_mail_actual.setText(str(cliente["mail"]))
        self.lb_medio_actual.setText(str(cliente["medio"]))


    def eliminarCliente(self):
        cliente = ControllerCliente()
        cliente.bajaCliente(self.le_dni_baja_cliente.text())
        self.le_dni_baja_cliente.clear()

    def pgMenuClienteModif(self):
        self.tableWidget_2.clear() 
        c = pymongo.MongoClient(serverSelectionTimeoutMs = 1000)
        db = c.get_database("Biblioteca")
        coleccionClientes = db.get_collection("Clientes")
        fila = 0
        for cliente in coleccionClientes.find():
            self.tableWidget_2.setItem(fila,0,QtWidgets.QTableWidgetItem(cliente["dni"]))
            self.tableWidget_2.setItem(fila,1,QtWidgets.QTableWidgetItem(cliente["nombre"]))
            self.tableWidget_2.setItem(fila,2,QtWidgets.QTableWidgetItem(cliente["apellido"]))
            self.tableWidget_2.setItem(fila,3,QtWidgets.QTableWidgetItem(cliente["mail"]))
            self.tableWidget_2.setItem(fila,4,QtWidgets.QTableWidgetItem(cliente["telefono"]))
            self.tableWidget_2.setItem(fila,5,QtWidgets.QTableWidgetItem(cliente["medio"]))
            fila += 1  
        self.stackedWidget.setCurrentWidget(self.page_menu_modificacion_cliente)

    #funciones de ejemplares METODOS
    def guardarEjemplar(self): 
        ejemplar = ControllerEjemplar()
        if self.cb_categoria.currentText() == "Libro":
            ejemplar.altaEjemplar(
                tipo = "Libro",
                titulo = self.le_titulo_ejemplar.text(),
                autor = self.le_autor_ejemplar.text(),
                fechaPublicacion = self.le_fecha_publicacion_ejemplar.text(),
                categoria = self.cb_categoria.currentText())
        elif self.cb_categoria.currentText() == "Revista":
            ejemplar.altaEjemplar(
                tipo = "Revista",
                titulo = self.le_titulo_ejemplar.text(),
                autor = self.le_autor_ejemplar.text(),
                fechaPublicacion = self.le_fecha_publicacion_ejemplar.text(),
                categoria = self.cb_categoria.currentText())
        elif self.cb_categoria.currentText() == "Diario":
            ejemplar.altaEjemplar(
                tipo = "Diario",
                titulo = self.le_titulo_ejemplar.text(),
                autor = self.le_autor_ejemplar.text(),
                fechaPublicacion = self.le_fecha_publicacion_ejemplar.text(),
                categoria = self.cb_categoria.currentText())
        else:
            print("Dato ingresado es invalido")

        self.le_titulo_ejemplar.clear()
        self.le_autor_ejemplar.clear()
        self.le_fecha_publicacion_ejemplar.clear()

    def mostarEjemplar(self):
        e = pymongo.MongoClient(serverSelectionTimeoutMS = 1000)
        db = e.get_database("Biblioteca")
        coleccionEjemplar = db.get_collection("Ejemplares")
       
        ejemplar = coleccionEjemplar.find_one({"titulo": self.le_titulo_mostrar_ejemplar.text()})
        print(ejemplar)
        self.lb_autor_mostrar_ejemplar.setText(str(ejemplar['autor']))
        self.lb_fechaPublicacion_mostrar_ejemplar.setText(str(ejemplar['fechaPublicacion']))
        self.lb_categoria_mostrar_ejemplar.setText(str(ejemplar['categoria']))
        self.le_titulo_mostrar_ejemplar.clear()

    def pgMostrarEjemplarVolver(self): 
        self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
        self.lb_autor_mostrar_ejemplar.clear()
        self.lb_fechaPublicacion_mostrar_ejemplar.clear()
        self.lb_categoria_mostrar_ejemplar.clear()

    def pgModificacionEjemplar(self):
        self.stackedWidget.setCurrentWidget(self.page_modificacion_ejemplar)
        e = pymongo.MongoClient(serverSelectionTimeoutMS = 1000)
        db = e.get_database("Biblioteca")
        coleccionEjemplar = db.get_collection("Ejemplares")
        ejemplar = coleccionEjemplar.find_one({"titulo": self.le_titutlo_modificar_ejemplar.text()})

        self.lb_titulo_actual.setText(str(ejemplar["titulo"]))
        self.lb_autor_actual.setText(str(ejemplar["autor"]))
        self.lb_fechaPublicacion_actual.setText(str(ejemplar["fechaPublicacion"]))
        self.lb_categoria_actual.setText(str(ejemplar["categoria"]))

    def guardarModificacionEjemplar(self):

        titulo = self.lb_titulo_actual.text()
        autor = self.lb_autor_actual.text()
        fechaPublicacion = self.lb_fechaPublicacion_actual.text()
        categoria = self.lb_categoria_actual.text()

        if self.le_titulo_nuevo.text() != "": 
            titulo = self.le_titulo_nuevo.text()
        if self.le_autor_nuevo.text() != "": 
            autor = self.le_autor_nuevo.text()
        if self.le_fechaPublicacion_nueva.text() != "": 
            fechaPublicacion = self.le_fechaPublicacion_nueva.text()
        if self.le_categoria_nueva.text() != "": 
            categoria = self.le_categoria_nueva.text()

        ejemplar = ControllerEjemplar()
        ejemplar.bajaEjemplar(self.lb_titulo_actual.text())
        ejemplar.altaEjemplar(categoria,titulo,autor,fechaPublicacion,categoria)

        self.lb_titulo_actual.clear()
        self.le_titulo_nuevo.clear()
        self.lb_autor_actual.clear()
        self.le_autor_nuevo.clear()
        self.lb_fechaPublicacion_actual.clear()
        self.le_fechaPublicacion_nueva.clear()
        self.lb_categoria_actual.clear()
        self.le_categoria_nueva.clear()

    def pgMenuClienteBaja(self): 
        self.tableWidget.clear() # nombre que le tengo que poner a la tabla
        c = pymongo.MongoClient(serverSelectionTimeoutMs = 1000)
        db = c.get_database("Biblioteca")
        coleccionClientes = db.get_collection("Clientes")
        fila = 0
        for cliente in coleccionClientes.find():
            self.tableWidget.setItem(fila,0,QtWidgets.QTableWidgetItem(cliente["dni"]))
            self.tableWidget.setItem(fila,1,QtWidgets.QTableWidgetItem(cliente["nombre"]))
            self.tableWidget.setItem(fila,2,QtWidgets.QTableWidgetItem(cliente["apellido"]))
            self.tableWidget.setItem(fila,3,QtWidgets.QTableWidgetItem(cliente["telefono"]))
            self.tableWidget.setItem(fila,4,QtWidgets.QTableWidgetItem(cliente["mail"]))
            self.tableWidget.setItem(fila,5,QtWidgets.QTableWidgetItem(cliente["medio"]))
            fila += 1  
        self.stackedWidget.setCurrentWidget(self.page_baja_cliente)

    def pgMenuEjemplarBaja(self): 
        self.tableWidget_3.clear()
        e = pymongo.MongoClient(serverSelectionTimeoutMs = 1000)
        db = e.get_database("Biblioteca")
        coleccionEjemplar = db.get_collection("Ejemplares")
        fila = 0
        for ejemplar in coleccionEjemplar.find():
            self.tableWidget_3.setItem(fila,0,QtWidgets.QTableWidgetItem(ejemplar["titulo"]))
            self.tableWidget_3.setItem(fila,1,QtWidgets.QTableWidgetItem(ejemplar["autor"]))
            self.tableWidget_3.setItem(fila,2,QtWidgets.QTableWidgetItem(ejemplar["fechaPublicacion"]))
            self.tableWidget_3.setItem(fila,3,QtWidgets.QTableWidgetItem(ejemplar["categoria"]))
            fila += 1    
        self.stackedWidget.setCurrentWidget(self.page_baja_ejemplar)


    def eliminarEjemplar(self):
        ejemplar = ControllerEjemplar()
        ejemplar.bajaEjemplar(self.le_titulo_baja_ejemplar.text())
        self.le_titulo_baja_ejemplar.clear()

    def pgMenuEjemplarModif(self): 
        self.tableWidget_4.clear()
        e = pymongo.MongoClient(serverSelectionTimeoutMs=1000)
        db = e.get_database("Biblioteca")
        coleccionEjemplares = db.get_collection("Ejemplares")
        fila = 0
        for ejemplar in coleccionEjemplares.find():
            self.tableWidget_4.setItem(fila, 0, QtWidgets.QTableWidgetItem(ejemplar["titulo"]))
            self.tableWidget_4.setItem(fila, 1, QtWidgets.QTableWidgetItem(ejemplar["autor"]))
            self.tableWidget_4.setItem(fila, 2, QtWidgets.QTableWidgetItem(ejemplar["fechaPublicacion"]))
            self.tableWidget_4.setItem(fila, 3, QtWidgets.QTableWidgetItem(ejemplar["categoria"]))
            fila += 1 
        self.stackedWidget.setCurrentWidget(self.page_menu_modificacion_ejemplar)

    def pgMenuEjemplar(self): self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
    def pgMenuEjemplarAlta(self): self.stackedWidget.setCurrentWidget(self.page_alta_ejemplar)
    def pgMenuEjemplarMostrarEjemplar(self): self.stackedWidget.setCurrentWidget(self.page_mostrar_ejemplar)
    def pgMenuEjemplarVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_principal)   
    def pgMenuAltaEjemplarVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
    def pgMenuBajaEjemplarVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
    def pgMenuModifEjemplarVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
    def pgModifEjemplarVolver(self): self.stackedWidget.setCurrentWidget(self.page_menu_ejemplar)
    def pgMenuModificacionEjemplar(self): self.stackedWidget.setCurrentWidget(self.page_menu_modificacion_ejemplar)


    #############################################################################################################################

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_cliente.setText(_translate("MainWindow", "Cliente"))
        self.bt_ejemplar.setText(_translate("MainWindow", "EJEMPLAR"))
        self.label_menu_principal.setText(_translate("MainWindow", "Menu Principal"))
        self.bt_alta_cliente.setText(_translate("MainWindow", "ALTA"))
        self.bt_baja_cliente.setText(_translate("MainWindow", "BAJA"))
        self.bt_modificacion_cliente.setText(_translate("MainWindow", "MODIFICACION"))
        self.bt_mostrar_cliente.setText(_translate("MainWindow", "MOSTRAR CLIENTE"))
        self.bt_volver_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.label.setText(_translate("MainWindow", "Menu Cliente"))
        self.label_menu_ejemplar.setText(_translate("MainWindow", "Menu Ejemplar"))
        self.bt_alta_ejemplar.setText(_translate("MainWindow", "ALTA"))
        self.bt_baja_ejemplar.setText(_translate("MainWindow", "BAJA"))
        self.bt_modificacion_ejemplar.setText(_translate("MainWindow", "MODIFICACION"))
        self.bt_mostrar_ejemplar.setText(_translate("MainWindow", "MOSTRAR EJEMPLARES"))
        self.bt_volver_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.label_2.setText(_translate("MainWindow", "Menu Alta Cliente"))
        self.bt_guardar_cliente.setText(_translate("MainWindow", "GUARDAR"))
        self.label_dni.setText(_translate("MainWindow", "DNI:"))
        self.cb_medio.setItemText(0, _translate("MainWindow", "SMS"))
        self.cb_medio.setItemText(1, _translate("MainWindow", "MAIL"))
        self.label_apellido.setText(_translate("MainWindow", "Apellido:"))
        self.label_nombre.setText(_translate("MainWindow", "Nombre:"))
        self.label_mail.setText(_translate("MainWindow", "Mail:"))
        self.label_medio.setText(_translate("MainWindow", "Medio:"))
        self.label_telefono.setText(_translate("MainWindow", "Telefono:"))
        self.bt_volver_menu_alta_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.label_3.setText(_translate("MainWindow", "Menu Baja Cliente"))
        self.label_4.setText(_translate("MainWindow", "DNI:"))
        self.bt_eliminar_cliente.setText(_translate("MainWindow", "ELIMINAR"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAIL"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "MEDIO"))
        self.bt_volver_baja_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.label_29.setText(_translate("MainWindow", "Menu Baja Ejemplar"))
        self.label_30.setText(_translate("MainWindow", "Titulo:"))
        self.bt_eliminar_ejemplar.setText(_translate("MainWindow", "ELIMINAR"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Autor"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fecha Publicacion"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Categoria"))
        self.bt_volver_baja_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.label_9.setText(_translate("MainWindow", "Menu Modificacion Cliente"))
        self.label_10.setText(_translate("MainWindow", "DNI:"))
        self.bt_modificar_modificar_cliente.setText(_translate("MainWindow", "MODIFICAR"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAIL"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "MEDIO"))
        self.bt_volver_menu_modificacion_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.label_36.setText(_translate("MainWindow", "Menu Modificacion Ejemplar"))
        self.label_37.setText(_translate("MainWindow", "Titulo:"))
        self.bt_modificar_modificar_ejemplar.setText(_translate("MainWindow", "MODIFICAR"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Autor"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fecha Publicacion"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Categoria"))
        self.bt_volver_menu_modificacion_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.label_11.setText(_translate("MainWindow", "Modificacion Cliente"))
        self.label_19.setText(_translate("MainWindow", "Numero Telefono Nuevo"))
        self.label_13.setText(_translate("MainWindow", "Nombre Nuevo:"))
        self.label_23.setText(_translate("MainWindow", "Medio Comunicacion Nuevo:"))
        self.label_18.setText(_translate("MainWindow", "Numero Telefono Actual:"))
        self.label_17.setText(_translate("MainWindow", "Dni Nuevo:"))
        self.cb_medio_nuevo.setItemText(0, _translate("MainWindow", "SMS"))
        self.cb_medio_nuevo.setItemText(1, _translate("MainWindow", "MAIL"))
        self.label_22.setText(_translate("MainWindow", "Medio Comunicacion Actual:"))
        self.label_21.setText(_translate("MainWindow", "Mail Nuevo:"))
        self.label_15.setText(_translate("MainWindow", "Apellido Nuevo:"))
        self.label_12.setText(_translate("MainWindow", "Nombre Actual:"))
        self.label_20.setText(_translate("MainWindow", "Mail Actual:"))
        self.label_14.setText(_translate("MainWindow", "Apellido Actual:"))
        self.label_16.setText(_translate("MainWindow", "Dni Actual:"))
        self.bt_volver_modificacion_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.bt_guardar_modificacion_cliente.setText(_translate("MainWindow", "GUARDAR"))
        self.label_38.setText(_translate("MainWindow", "Modificacion Ejemplar"))
        self.label_39.setText(_translate("MainWindow", "Titulo Actual:"))
        self.label_40.setText(_translate("MainWindow", "Titulo Nuevo:"))
        self.label_41.setText(_translate("MainWindow", "Autor Actual:"))
        self.label_42.setText(_translate("MainWindow", "Autor Nuevo:"))
        self.label_43.setText(_translate("MainWindow", "Fecha Publicacion Actual:"))
        self.label_44.setText(_translate("MainWindow", "Fecha Publicacion Nueva:"))
        self.label_48.setText(_translate("MainWindow", "Categoria Actual:"))
        self.label_50.setText(_translate("MainWindow", "Categoria Nueva:"))
        self.bt_volver_modificacion_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.bt_guardar_modificacion_ejemplar.setText(_translate("MainWindow", "GUARDAR"))
        self.label_8.setText(_translate("MainWindow", "Menu Mostrar Cliente"))
        self.label_dni_2.setText(_translate("MainWindow", "DNI:"))
        self.label_nombre_2.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Apellido:"))
        self.label_6.setText(_translate("MainWindow", "Telefono:"))
        self.label_7.setText(_translate("MainWindow", "Mail:"))
        self.label_medio_2.setText(_translate("MainWindow", "Medio:"))
        self.bt_volver_mostrar_cliente.setText(_translate("MainWindow", "VOLVER"))
        self.bt_mostrar_mostrar_cliente.setText(_translate("MainWindow", "MOSTRAR"))
        self.label_31.setText(_translate("MainWindow", "Menu Mostrar Ejemplares"))
        self.label_32.setText(_translate("MainWindow", "Titulo:"))
        self.label_33.setText(_translate("MainWindow", "Autor:"))
        self.label_34.setText(_translate("MainWindow", "Fecha Publicacion:"))
        self.label_35.setText(_translate("MainWindow", "Categoria:"))
        self.bt_volver_mostrar_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.bt_mostrar_mostrar_ejemplar.setText(_translate("MainWindow", "MOSTRAR"))
        self.label_24.setText(_translate("MainWindow", "Menu Alta Ejemplar"))
        self.label_25.setText(_translate("MainWindow", "Titulo:"))
        self.label_26.setText(_translate("MainWindow", "Autor:"))
        self.label_27.setText(_translate("MainWindow", "Fecha Publicacion:"))
        self.label_28.setText(_translate("MainWindow", "Categoria:"))
        self.cb_categoria.setItemText(0, _translate("MainWindow", "Diario"))
        self.cb_categoria.setItemText(1, _translate("MainWindow", "Revista"))
        self.cb_categoria.setItemText(2, _translate("MainWindow", "Libro"))
        self.bt_volver_menu_alta_ejemplar.setText(_translate("MainWindow", "VOLVER"))
        self.bt_guardar_ejemplar.setText(_translate("MainWindow", "GUARDAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
